.PHONY: all generate

IBST_ROOT=/path/to/ibst
INPUT=/path/to/ibst/Input
OVERRIDES=/path/to/ibst/Overrides
OUTPUT=/path/to/ibst/Output
REQUIREMENTS=/path/to/ibst/requirements.txt

generate:
	python3.8 generate_yocto_manifest.py --ibst-root $(IBST_ROOT) --input $(INPUT) --overrides $(OVERRIDES) --output $(OUTPUT) --requirements $(REQUIREMENTS)
