#!/bin/bash
#INTEL CONFIDENTIAL
#****************************************************************************
# This file, software, or program is supplied under the terms of a license
# agreement or nondisclosure agreement with INTEL Corporation and may not be
# copied or disclosed except in accordance with the terms of that agreement.
#****************************************************************************

#
# update_automation wrapper script
#

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
${SCRIPT_DIR}/update_val_tools.py $*
exit $?

